# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: farfly.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x66\x61rfly.proto\x12\x06\x66\x61rfly\"\x07\n\x05\x45mpty\"#\n\x0bJsonRequest\x12\x14\n\x0cjson_payload\x18\x01 \x01(\t\"6\n\tJsonReply\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x12\x14\n\x0cjson_payload\x18\x02 \x01(\t2\xe9\x02\n\x16\x46\x61rflySchedulerService\x12*\n\x06Health\x12\r.farfly.Empty\x1a\x11.farfly.JsonReply\x12+\n\x07Metrics\x12\r.farfly.Empty\x1a\x11.farfly.JsonReply\x12(\n\x04Plan\x12\r.farfly.Empty\x1a\x11.farfly.JsonReply\x12\x31\n\rRecomputePlan\x12\r.farfly.Empty\x1a\x11.farfly.JsonReply\x12.\n\nReloadPlan\x12\r.farfly.Empty\x1a\x11.farfly.JsonReply\x12\x30\n\x06Submit\x12\x13.farfly.JsonRequest\x1a\x11.farfly.JsonReply\x12\x37\n\rReportCredits\x12\x13.farfly.JsonRequest\x1a\x11.farfly.JsonReply2\xdb\x01\n\rServerService\x12*\n\x06Health\x12\r.farfly.Empty\x1a\x11.farfly.JsonReply\x12+\n\x07Metrics\x12\r.farfly.Empty\x1a\x11.farfly.JsonReply\x12\x39\n\x0fUpdatePlacement\x12\x13.farfly.JsonRequest\x1a\x11.farfly.JsonReply\x12\x36\n\x0c\x45xecuteBatch\x12\x13.farfly.JsonRequest\x1a\x11.farfly.JsonReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'farfly_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=24
  _globals['_EMPTY']._serialized_end=31
  _globals['_JSONREQUEST']._serialized_start=33
  _globals['_JSONREQUEST']._serialized_end=68
  _globals['_JSONREPLY']._serialized_start=70
  _globals['_JSONREPLY']._serialized_end=124
  _globals['_FARFLYSCHEDULERSERVICE']._serialized_start=127
  _globals['_FARFLYSCHEDULERSERVICE']._serialized_end=488
  _globals['_SERVERSERVICE']._serialized_start=491
  _globals['_SERVERSERVICE']._serialized_end=710
# @@protoc_insertion_point(module_scope)
