# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import farfly_pb2 as farfly__pb2


class FarflySchedulerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/farfly.FarflySchedulerService/Health',
                request_serializer=farfly__pb2.Empty.SerializeToString,
                response_deserializer=farfly__pb2.JsonReply.FromString,
                )
        self.Metrics = channel.unary_unary(
                '/farfly.FarflySchedulerService/Metrics',
                request_serializer=farfly__pb2.Empty.SerializeToString,
                response_deserializer=farfly__pb2.JsonReply.FromString,
                )
        self.Plan = channel.unary_unary(
                '/farfly.FarflySchedulerService/Plan',
                request_serializer=farfly__pb2.Empty.SerializeToString,
                response_deserializer=farfly__pb2.JsonReply.FromString,
                )
        self.RecomputePlan = channel.unary_unary(
                '/farfly.FarflySchedulerService/RecomputePlan',
                request_serializer=farfly__pb2.Empty.SerializeToString,
                response_deserializer=farfly__pb2.JsonReply.FromString,
                )
        self.ReloadPlan = channel.unary_unary(
                '/farfly.FarflySchedulerService/ReloadPlan',
                request_serializer=farfly__pb2.Empty.SerializeToString,
                response_deserializer=farfly__pb2.JsonReply.FromString,
                )
        self.Submit = channel.unary_unary(
                '/farfly.FarflySchedulerService/Submit',
                request_serializer=farfly__pb2.JsonRequest.SerializeToString,
                response_deserializer=farfly__pb2.JsonReply.FromString,
                )
        self.ReportCredits = channel.unary_unary(
                '/farfly.FarflySchedulerService/ReportCredits',
                request_serializer=farfly__pb2.JsonRequest.SerializeToString,
                response_deserializer=farfly__pb2.JsonReply.FromString,
                )


class FarflySchedulerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Metrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Plan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecomputePlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReloadPlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Submit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportCredits(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FarflySchedulerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=farfly__pb2.Empty.FromString,
                    response_serializer=farfly__pb2.JsonReply.SerializeToString,
            ),
            'Metrics': grpc.unary_unary_rpc_method_handler(
                    servicer.Metrics,
                    request_deserializer=farfly__pb2.Empty.FromString,
                    response_serializer=farfly__pb2.JsonReply.SerializeToString,
            ),
            'Plan': grpc.unary_unary_rpc_method_handler(
                    servicer.Plan,
                    request_deserializer=farfly__pb2.Empty.FromString,
                    response_serializer=farfly__pb2.JsonReply.SerializeToString,
            ),
            'RecomputePlan': grpc.unary_unary_rpc_method_handler(
                    servicer.RecomputePlan,
                    request_deserializer=farfly__pb2.Empty.FromString,
                    response_serializer=farfly__pb2.JsonReply.SerializeToString,
            ),
            'ReloadPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.ReloadPlan,
                    request_deserializer=farfly__pb2.Empty.FromString,
                    response_serializer=farfly__pb2.JsonReply.SerializeToString,
            ),
            'Submit': grpc.unary_unary_rpc_method_handler(
                    servicer.Submit,
                    request_deserializer=farfly__pb2.JsonRequest.FromString,
                    response_serializer=farfly__pb2.JsonReply.SerializeToString,
            ),
            'ReportCredits': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportCredits,
                    request_deserializer=farfly__pb2.JsonRequest.FromString,
                    response_serializer=farfly__pb2.JsonReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'farfly.FarflySchedulerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FarflySchedulerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/farfly.FarflySchedulerService/Health',
            farfly__pb2.Empty.SerializeToString,
            farfly__pb2.JsonReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Metrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/farfly.FarflySchedulerService/Metrics',
            farfly__pb2.Empty.SerializeToString,
            farfly__pb2.JsonReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Plan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/farfly.FarflySchedulerService/Plan',
            farfly__pb2.Empty.SerializeToString,
            farfly__pb2.JsonReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RecomputePlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/farfly.FarflySchedulerService/RecomputePlan',
            farfly__pb2.Empty.SerializeToString,
            farfly__pb2.JsonReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReloadPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/farfly.FarflySchedulerService/ReloadPlan',
            farfly__pb2.Empty.SerializeToString,
            farfly__pb2.JsonReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Submit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/farfly.FarflySchedulerService/Submit',
            farfly__pb2.JsonRequest.SerializeToString,
            farfly__pb2.JsonReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReportCredits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/farfly.FarflySchedulerService/ReportCredits',
            farfly__pb2.JsonRequest.SerializeToString,
            farfly__pb2.JsonReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class ServerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/farfly.ServerService/Health',
                request_serializer=farfly__pb2.Empty.SerializeToString,
                response_deserializer=farfly__pb2.JsonReply.FromString,
                )
        self.Metrics = channel.unary_unary(
                '/farfly.ServerService/Metrics',
                request_serializer=farfly__pb2.Empty.SerializeToString,
                response_deserializer=farfly__pb2.JsonReply.FromString,
                )
        self.UpdatePlacement = channel.unary_unary(
                '/farfly.ServerService/UpdatePlacement',
                request_serializer=farfly__pb2.JsonRequest.SerializeToString,
                response_deserializer=farfly__pb2.JsonReply.FromString,
                )
        self.ExecuteBatch = channel.unary_unary(
                '/farfly.ServerService/ExecuteBatch',
                request_serializer=farfly__pb2.JsonRequest.SerializeToString,
                response_deserializer=farfly__pb2.JsonReply.FromString,
                )


class ServerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Metrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePlacement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=farfly__pb2.Empty.FromString,
                    response_serializer=farfly__pb2.JsonReply.SerializeToString,
            ),
            'Metrics': grpc.unary_unary_rpc_method_handler(
                    servicer.Metrics,
                    request_deserializer=farfly__pb2.Empty.FromString,
                    response_serializer=farfly__pb2.JsonReply.SerializeToString,
            ),
            'UpdatePlacement': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePlacement,
                    request_deserializer=farfly__pb2.JsonRequest.FromString,
                    response_serializer=farfly__pb2.JsonReply.SerializeToString,
            ),
            'ExecuteBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteBatch,
                    request_deserializer=farfly__pb2.JsonRequest.FromString,
                    response_serializer=farfly__pb2.JsonReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'farfly.ServerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ServerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/farfly.ServerService/Health',
            farfly__pb2.Empty.SerializeToString,
            farfly__pb2.JsonReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Metrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/farfly.ServerService/Metrics',
            farfly__pb2.Empty.SerializeToString,
            farfly__pb2.JsonReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdatePlacement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/farfly.ServerService/UpdatePlacement',
            farfly__pb2.JsonRequest.SerializeToString,
            farfly__pb2.JsonReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExecuteBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/farfly.ServerService/ExecuteBatch',
            farfly__pb2.JsonRequest.SerializeToString,
            farfly__pb2.JsonReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
